services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${APP_NAME}
    container_name: ${APP_NAME}
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - /var/www/public/build
    ports:
      - ${APP_PORT}:9000
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME}-db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 3316:3306
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${APP_NAME}-phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME}-nginx
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - .:/var/www
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - app

volumes:
  db_data:
